import json
import logging
import os
import sys
from datetime import datetime, timezone

# Add the parent directory to sys.path so we can import app
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from app.database import SessionLocal
from app import models

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

def ingest_airports_from_file(path: str = "data/perplexity_airports.json"):
    """
    Ingest airport status from an offline JSON file generated by Perplexity.
    """
    if not os.path.exists(path):
        logger.error(f"File not found: {path}")
        return

    try:
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        logger.error(f"Invalid JSON in {path}: {e}")
        return
    except Exception as e:
        logger.error(f"Error reading {path}: {e}")
        return

    airports_data = data.get("airports", [])
    if not airports_data:
        logger.warning(f"No 'airports' array found in {path}")
        return

    db = SessionLocal()
    try:
        logger.info(f"Starting ingestion of {len(airports_data)} airports from {path}...")
        
        status_map = {
            "OPEN": models.StatusEnum.OPEN,
            "RESTRICTED": models.StatusEnum.RESTRICTED,
            "CLOSED": models.StatusEnum.CLOSED,
            "UNKNOWN": models.StatusEnum.UNKNOWN,
        }

        for item in airports_data:
            icao = item.get("icao")
            if not icao:
                continue

            airport = db.query(models.Airport).filter(models.Airport.icao == icao).first()
            if not airport:
                logger.warning(f"Airport {icao} not found in DB, skipping.")
                continue

            api_status = item.get("status", "UNKNOWN").upper()
            airport.status = status_map.get(api_status, models.StatusEnum.UNKNOWN)
            airport.status_reason = item.get("status_reason")
            airport.status_source = item.get("status_source_url")
            airport.status_last_updated = datetime.now(timezone.utc)
            
            # Optional Advisory
            # Since the requirement says "Optionally create an Advisory", we'll create it.
            # Avoid duplicating identical advisories if run multiple times.
            advisory_title = f"Update for {icao} from offline ingestion"
            source_url = item.get("status_source_url")
            summary = item.get("status_reason")
            
            existing_advisory = db.query(models.Advisory).filter(
                models.Advisory.title == advisory_title,
                models.Advisory.summary == summary
            ).first()
            
            if not existing_advisory:
                advisory = models.Advisory(
                    source_type=models.AdvisorySourceType.AIRPORT, 
                    source_name=item.get("status_source_name", "Perplexity JSON Ingest"),
                    source_url=source_url,
                    title=advisory_title,
                    summary=summary,
                    airports_icao=[icao],
                )
                db.add(advisory)

        db.commit()
        logger.info("Successfully ingested offline airport data and committed to the database.")
    except Exception as e:
        db.rollback()
        logger.error(f"Failed to ingest airport data: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    # If a custom path is provided as the first argument, use it; otherwise default to data/perplexity_airports.json
    custom_path = sys.argv[1] if len(sys.argv) > 1 else "data/perplexity_airports.json"
    ingest_airports_from_file(custom_path)
